name: projectname33

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  path_provider: ^0.5.0+1
  provider: ^4.3.2+1
  http: ^0.12.0+4
  shared_preferences: ^2.0.5
  fluttertoast: ^8.0.8
  url_launcher: ^6.0.4
  http_parser: ^3.1.4
#  image_picker: ^0.6.7+10
  dropdown_below: ^0.0.7
  google_maps_flutter: ^2.0.3
  flutter_polyline_points: ^0.2.4
  geolocator: ^5.3.2
  firebase_core: ^1.4.0
  firebase_messaging: ^10.0.0
  flutter_local_notifications: ^5.0.0+4
  image_picker_saver: ^0.3.0
  floatingpanel: ^1.1.3
  flutter_speed_dial: ^3.0.5
  location: ^2.1.0
#  flutter_mapbox_navigation: ^0.0.26
#  cloud_firestore: ^0.13.3
#  device_id: ^0.1.3
#  device_info: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icon.jpg
    - assets/picture.jpg
    - assets/images/logo_1.png
    - assets/images/shop.png
    - assets/images/no_image.png
    - assets/images/settings.jpg
    - assets/images/balance_cod.jpg
    - assets/images/size.png
    - assets/images/weight.png
    - assets/images/quantity.png
    - assets/images/call-icon.png
    - assets/images/chat-icon.png
    - assets/images/locationicon.png
    - assets/images/eye-icon.png
    - assets/images/strike-eye.png
    - assets/images/direction.png
    - assets/images/balance-icon.png
    - assets/images/cancel-icon.png
    - assets/images/report-icon.png
    - assets/images/location-icon.png
    - assets/images/homemade.jpg
